# Generated by Django 3.2.7 on 2021-09-14 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_created=datetime.datetime(2021, 9, 14, 6, 16, 47, 196773, tzinfo=utc))),
                ('user', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_answered', models.DateTimeField(auto_created=datetime.datetime(2021, 9, 14, 6, 16, 47, 197210, tzinfo=utc))),
                ('answer', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
    ]
