# Generated by Django 3.2.7 on 2021-09-14 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_answered',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_added',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 9, 14, 6, 18, 45, 994179, tzinfo=utc)),
        ),
    ]
