# Generated by Django 3.2.7 on 2021-09-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_question_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
